# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Dokumente\ec-spride-ecp-uc-improved

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Dokumente\ec-spride-ecp-uc-improved

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2017.2.3\bin\cmake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Dokumente\ec-spride-ecp-uc-improved\CMakeFiles D:\Dokumente\ec-spride-ecp-uc-improved\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Dokumente\ec-spride-ecp-uc-improved\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GAMMA_LIB

# Build rule for target.
GAMMA_LIB: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 GAMMA_LIB
.PHONY : GAMMA_LIB

# fast build rule for target.
GAMMA_LIB/fast:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/build
.PHONY : GAMMA_LIB/fast

#=============================================================================
# Target rules for targets named UC

# Build rule for target.
UC: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 UC
.PHONY : UC

# fast build rule for target.
UC/fast:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/build
.PHONY : UC/fast

#=============================================================================
# Target rules for targets named bristol

# Build rule for target.
bristol: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 bristol
.PHONY : bristol

# fast build rule for target.
bristol/fast:
	$(MAKE) -f CMakeFiles\bristol.dir\build.make CMakeFiles/bristol.dir/build
.PHONY : bristol/fast

src/Gamma/gamma/gamma1.obj: src/Gamma/gamma/gamma1.cpp.obj

.PHONY : src/Gamma/gamma/gamma1.obj

# target to build an object file
src/Gamma/gamma/gamma1.cpp.obj:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/gamma/gamma1.cpp.obj
.PHONY : src/Gamma/gamma/gamma1.cpp.obj

src/Gamma/gamma/gamma1.i: src/Gamma/gamma/gamma1.cpp.i

.PHONY : src/Gamma/gamma/gamma1.i

# target to preprocess a source file
src/Gamma/gamma/gamma1.cpp.i:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/gamma/gamma1.cpp.i
.PHONY : src/Gamma/gamma/gamma1.cpp.i

src/Gamma/gamma/gamma1.s: src/Gamma/gamma/gamma1.cpp.s

.PHONY : src/Gamma/gamma/gamma1.s

# target to generate assembly for a file
src/Gamma/gamma/gamma1.cpp.s:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/gamma/gamma1.cpp.s
.PHONY : src/Gamma/gamma/gamma1.cpp.s

src/Gamma/gamma/gamma2.obj: src/Gamma/gamma/gamma2.cpp.obj

.PHONY : src/Gamma/gamma/gamma2.obj

# target to build an object file
src/Gamma/gamma/gamma2.cpp.obj:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/gamma/gamma2.cpp.obj
.PHONY : src/Gamma/gamma/gamma2.cpp.obj

src/Gamma/gamma/gamma2.i: src/Gamma/gamma/gamma2.cpp.i

.PHONY : src/Gamma/gamma/gamma2.i

# target to preprocess a source file
src/Gamma/gamma/gamma2.cpp.i:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/gamma/gamma2.cpp.i
.PHONY : src/Gamma/gamma/gamma2.cpp.i

src/Gamma/gamma/gamma2.s: src/Gamma/gamma/gamma2.cpp.s

.PHONY : src/Gamma/gamma/gamma2.s

# target to generate assembly for a file
src/Gamma/gamma/gamma2.cpp.s:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/gamma/gamma2.cpp.s
.PHONY : src/Gamma/gamma/gamma2.cpp.s

src/Gamma/util/SHDL_to_SHDL.obj: src/Gamma/util/SHDL_to_SHDL.cpp.obj

.PHONY : src/Gamma/util/SHDL_to_SHDL.obj

# target to build an object file
src/Gamma/util/SHDL_to_SHDL.cpp.obj:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/util/SHDL_to_SHDL.cpp.obj
.PHONY : src/Gamma/util/SHDL_to_SHDL.cpp.obj

src/Gamma/util/SHDL_to_SHDL.i: src/Gamma/util/SHDL_to_SHDL.cpp.i

.PHONY : src/Gamma/util/SHDL_to_SHDL.i

# target to preprocess a source file
src/Gamma/util/SHDL_to_SHDL.cpp.i:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/util/SHDL_to_SHDL.cpp.i
.PHONY : src/Gamma/util/SHDL_to_SHDL.cpp.i

src/Gamma/util/SHDL_to_SHDL.s: src/Gamma/util/SHDL_to_SHDL.cpp.s

.PHONY : src/Gamma/util/SHDL_to_SHDL.s

# target to generate assembly for a file
src/Gamma/util/SHDL_to_SHDL.cpp.s:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/util/SHDL_to_SHDL.cpp.s
.PHONY : src/Gamma/util/SHDL_to_SHDL.cpp.s

src/Gamma/util/print_graph.obj: src/Gamma/util/print_graph.cpp.obj

.PHONY : src/Gamma/util/print_graph.obj

# target to build an object file
src/Gamma/util/print_graph.cpp.obj:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/util/print_graph.cpp.obj
.PHONY : src/Gamma/util/print_graph.cpp.obj

src/Gamma/util/print_graph.i: src/Gamma/util/print_graph.cpp.i

.PHONY : src/Gamma/util/print_graph.i

# target to preprocess a source file
src/Gamma/util/print_graph.cpp.i:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/util/print_graph.cpp.i
.PHONY : src/Gamma/util/print_graph.cpp.i

src/Gamma/util/print_graph.s: src/Gamma/util/print_graph.cpp.s

.PHONY : src/Gamma/util/print_graph.s

# target to generate assembly for a file
src/Gamma/util/print_graph.cpp.s:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/util/print_graph.cpp.s
.PHONY : src/Gamma/util/print_graph.cpp.s

src/Gamma/util/read_SHDL.obj: src/Gamma/util/read_SHDL.cpp.obj

.PHONY : src/Gamma/util/read_SHDL.obj

# target to build an object file
src/Gamma/util/read_SHDL.cpp.obj:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/util/read_SHDL.cpp.obj
.PHONY : src/Gamma/util/read_SHDL.cpp.obj

src/Gamma/util/read_SHDL.i: src/Gamma/util/read_SHDL.cpp.i

.PHONY : src/Gamma/util/read_SHDL.i

# target to preprocess a source file
src/Gamma/util/read_SHDL.cpp.i:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/util/read_SHDL.cpp.i
.PHONY : src/Gamma/util/read_SHDL.cpp.i

src/Gamma/util/read_SHDL.s: src/Gamma/util/read_SHDL.cpp.s

.PHONY : src/Gamma/util/read_SHDL.s

# target to generate assembly for a file
src/Gamma/util/read_SHDL.cpp.s:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/Gamma/util/read_SHDL.cpp.s
.PHONY : src/Gamma/util/read_SHDL.cpp.s

src/UC.obj: src/UC.cpp.obj

.PHONY : src/UC.obj

# target to build an object file
src/UC.cpp.obj:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/UC.cpp.obj
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/UC.cpp.obj
.PHONY : src/UC.cpp.obj

src/UC.i: src/UC.cpp.i

.PHONY : src/UC.i

# target to preprocess a source file
src/UC.cpp.i:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/UC.cpp.i
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/UC.cpp.i
.PHONY : src/UC.cpp.i

src/UC.s: src/UC.cpp.s

.PHONY : src/UC.s

# target to generate assembly for a file
src/UC.cpp.s:
	$(MAKE) -f CMakeFiles\GAMMA_LIB.dir\build.make CMakeFiles/GAMMA_LIB.dir/src/UC.cpp.s
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/UC.cpp.s
.PHONY : src/UC.cpp.s

src/bristol_to_SHDL.obj: src/bristol_to_SHDL.cpp.obj

.PHONY : src/bristol_to_SHDL.obj

# target to build an object file
src/bristol_to_SHDL.cpp.obj:
	$(MAKE) -f CMakeFiles\bristol.dir\build.make CMakeFiles/bristol.dir/src/bristol_to_SHDL.cpp.obj
.PHONY : src/bristol_to_SHDL.cpp.obj

src/bristol_to_SHDL.i: src/bristol_to_SHDL.cpp.i

.PHONY : src/bristol_to_SHDL.i

# target to preprocess a source file
src/bristol_to_SHDL.cpp.i:
	$(MAKE) -f CMakeFiles\bristol.dir\build.make CMakeFiles/bristol.dir/src/bristol_to_SHDL.cpp.i
.PHONY : src/bristol_to_SHDL.cpp.i

src/bristol_to_SHDL.s: src/bristol_to_SHDL.cpp.s

.PHONY : src/bristol_to_SHDL.s

# target to generate assembly for a file
src/bristol_to_SHDL.cpp.s:
	$(MAKE) -f CMakeFiles\bristol.dir\build.make CMakeFiles/bristol.dir/src/bristol_to_SHDL.cpp.s
.PHONY : src/bristol_to_SHDL.cpp.s

src/debug.obj: src/debug.cpp.obj

.PHONY : src/debug.obj

# target to build an object file
src/debug.cpp.obj:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/debug.cpp.obj
.PHONY : src/debug.cpp.obj

src/debug.i: src/debug.cpp.i

.PHONY : src/debug.i

# target to preprocess a source file
src/debug.cpp.i:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/debug.cpp.i
.PHONY : src/debug.cpp.i

src/debug.s: src/debug.cpp.s

.PHONY : src/debug.s

# target to generate assembly for a file
src/debug.cpp.s:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/debug.cpp.s
.PHONY : src/debug.cpp.s

src/uc/2way/embedding.obj: src/uc/2way/embedding.cpp.obj

.PHONY : src/uc/2way/embedding.obj

# target to build an object file
src/uc/2way/embedding.cpp.obj:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/2way/embedding.cpp.obj
.PHONY : src/uc/2way/embedding.cpp.obj

src/uc/2way/embedding.i: src/uc/2way/embedding.cpp.i

.PHONY : src/uc/2way/embedding.i

# target to preprocess a source file
src/uc/2way/embedding.cpp.i:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/2way/embedding.cpp.i
.PHONY : src/uc/2way/embedding.cpp.i

src/uc/2way/embedding.s: src/uc/2way/embedding.cpp.s

.PHONY : src/uc/2way/embedding.s

# target to generate assembly for a file
src/uc/2way/embedding.cpp.s:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/2way/embedding.cpp.s
.PHONY : src/uc/2way/embedding.cpp.s

src/uc/2way/node.obj: src/uc/2way/node.cpp.obj

.PHONY : src/uc/2way/node.obj

# target to build an object file
src/uc/2way/node.cpp.obj:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/2way/node.cpp.obj
.PHONY : src/uc/2way/node.cpp.obj

src/uc/2way/node.i: src/uc/2way/node.cpp.i

.PHONY : src/uc/2way/node.i

# target to preprocess a source file
src/uc/2way/node.cpp.i:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/2way/node.cpp.i
.PHONY : src/uc/2way/node.cpp.i

src/uc/2way/node.s: src/uc/2way/node.cpp.s

.PHONY : src/uc/2way/node.s

# target to generate assembly for a file
src/uc/2way/node.cpp.s:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/2way/node.cpp.s
.PHONY : src/uc/2way/node.cpp.s

src/uc/2way/print_circuit.obj: src/uc/2way/print_circuit.cpp.obj

.PHONY : src/uc/2way/print_circuit.obj

# target to build an object file
src/uc/2way/print_circuit.cpp.obj:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/2way/print_circuit.cpp.obj
.PHONY : src/uc/2way/print_circuit.cpp.obj

src/uc/2way/print_circuit.i: src/uc/2way/print_circuit.cpp.i

.PHONY : src/uc/2way/print_circuit.i

# target to preprocess a source file
src/uc/2way/print_circuit.cpp.i:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/2way/print_circuit.cpp.i
.PHONY : src/uc/2way/print_circuit.cpp.i

src/uc/2way/print_circuit.s: src/uc/2way/print_circuit.cpp.s

.PHONY : src/uc/2way/print_circuit.s

# target to generate assembly for a file
src/uc/2way/print_circuit.cpp.s:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/2way/print_circuit.cpp.s
.PHONY : src/uc/2way/print_circuit.cpp.s

src/uc/2way/valiant.obj: src/uc/2way/valiant.cpp.obj

.PHONY : src/uc/2way/valiant.obj

# target to build an object file
src/uc/2way/valiant.cpp.obj:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/2way/valiant.cpp.obj
.PHONY : src/uc/2way/valiant.cpp.obj

src/uc/2way/valiant.i: src/uc/2way/valiant.cpp.i

.PHONY : src/uc/2way/valiant.i

# target to preprocess a source file
src/uc/2way/valiant.cpp.i:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/2way/valiant.cpp.i
.PHONY : src/uc/2way/valiant.cpp.i

src/uc/2way/valiant.s: src/uc/2way/valiant.cpp.s

.PHONY : src/uc/2way/valiant.s

# target to generate assembly for a file
src/uc/2way/valiant.cpp.s:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/2way/valiant.cpp.s
.PHONY : src/uc/2way/valiant.cpp.s

src/uc/4way/Block.obj: src/uc/4way/Block.cpp.obj

.PHONY : src/uc/4way/Block.obj

# target to build an object file
src/uc/4way/Block.cpp.obj:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/4way/Block.cpp.obj
.PHONY : src/uc/4way/Block.cpp.obj

src/uc/4way/Block.i: src/uc/4way/Block.cpp.i

.PHONY : src/uc/4way/Block.i

# target to preprocess a source file
src/uc/4way/Block.cpp.i:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/4way/Block.cpp.i
.PHONY : src/uc/4way/Block.cpp.i

src/uc/4way/Block.s: src/uc/4way/Block.cpp.s

.PHONY : src/uc/4way/Block.s

# target to generate assembly for a file
src/uc/4way/Block.cpp.s:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/4way/Block.cpp.s
.PHONY : src/uc/4way/Block.cpp.s

src/uc/4way/UCNode.obj: src/uc/4way/UCNode.cpp.obj

.PHONY : src/uc/4way/UCNode.obj

# target to build an object file
src/uc/4way/UCNode.cpp.obj:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/4way/UCNode.cpp.obj
.PHONY : src/uc/4way/UCNode.cpp.obj

src/uc/4way/UCNode.i: src/uc/4way/UCNode.cpp.i

.PHONY : src/uc/4way/UCNode.i

# target to preprocess a source file
src/uc/4way/UCNode.cpp.i:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/4way/UCNode.cpp.i
.PHONY : src/uc/4way/UCNode.cpp.i

src/uc/4way/UCNode.s: src/uc/4way/UCNode.cpp.s

.PHONY : src/uc/4way/UCNode.s

# target to generate assembly for a file
src/uc/4way/UCNode.cpp.s:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/4way/UCNode.cpp.s
.PHONY : src/uc/4way/UCNode.cpp.s

src/uc/4way/ValiantEUG.obj: src/uc/4way/ValiantEUG.cpp.obj

.PHONY : src/uc/4way/ValiantEUG.obj

# target to build an object file
src/uc/4way/ValiantEUG.cpp.obj:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/4way/ValiantEUG.cpp.obj
.PHONY : src/uc/4way/ValiantEUG.cpp.obj

src/uc/4way/ValiantEUG.i: src/uc/4way/ValiantEUG.cpp.i

.PHONY : src/uc/4way/ValiantEUG.i

# target to preprocess a source file
src/uc/4way/ValiantEUG.cpp.i:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/4way/ValiantEUG.cpp.i
.PHONY : src/uc/4way/ValiantEUG.cpp.i

src/uc/4way/ValiantEUG.s: src/uc/4way/ValiantEUG.cpp.s

.PHONY : src/uc/4way/ValiantEUG.s

# target to generate assembly for a file
src/uc/4way/ValiantEUG.cpp.s:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/4way/ValiantEUG.cpp.s
.PHONY : src/uc/4way/ValiantEUG.cpp.s

src/uc/4way/ValiantUC.obj: src/uc/4way/ValiantUC.cpp.obj

.PHONY : src/uc/4way/ValiantUC.obj

# target to build an object file
src/uc/4way/ValiantUC.cpp.obj:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/4way/ValiantUC.cpp.obj
.PHONY : src/uc/4way/ValiantUC.cpp.obj

src/uc/4way/ValiantUC.i: src/uc/4way/ValiantUC.cpp.i

.PHONY : src/uc/4way/ValiantUC.i

# target to preprocess a source file
src/uc/4way/ValiantUC.cpp.i:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/4way/ValiantUC.cpp.i
.PHONY : src/uc/4way/ValiantUC.cpp.i

src/uc/4way/ValiantUC.s: src/uc/4way/ValiantUC.cpp.s

.PHONY : src/uc/4way/ValiantUC.s

# target to generate assembly for a file
src/uc/4way/ValiantUC.cpp.s:
	$(MAKE) -f CMakeFiles\UC.dir\build.make CMakeFiles/UC.dir/src/uc/4way/ValiantUC.cpp.s
.PHONY : src/uc/4way/ValiantUC.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... GAMMA_LIB
	@echo ... UC
	@echo ... edit_cache
	@echo ... bristol
	@echo ... rebuild_cache
	@echo ... src/Gamma/gamma/gamma1.obj
	@echo ... src/Gamma/gamma/gamma1.i
	@echo ... src/Gamma/gamma/gamma1.s
	@echo ... src/Gamma/gamma/gamma2.obj
	@echo ... src/Gamma/gamma/gamma2.i
	@echo ... src/Gamma/gamma/gamma2.s
	@echo ... src/Gamma/util/SHDL_to_SHDL.obj
	@echo ... src/Gamma/util/SHDL_to_SHDL.i
	@echo ... src/Gamma/util/SHDL_to_SHDL.s
	@echo ... src/Gamma/util/print_graph.obj
	@echo ... src/Gamma/util/print_graph.i
	@echo ... src/Gamma/util/print_graph.s
	@echo ... src/Gamma/util/read_SHDL.obj
	@echo ... src/Gamma/util/read_SHDL.i
	@echo ... src/Gamma/util/read_SHDL.s
	@echo ... src/UC.obj
	@echo ... src/UC.i
	@echo ... src/UC.s
	@echo ... src/bristol_to_SHDL.obj
	@echo ... src/bristol_to_SHDL.i
	@echo ... src/bristol_to_SHDL.s
	@echo ... src/debug.obj
	@echo ... src/debug.i
	@echo ... src/debug.s
	@echo ... src/uc/2way/embedding.obj
	@echo ... src/uc/2way/embedding.i
	@echo ... src/uc/2way/embedding.s
	@echo ... src/uc/2way/node.obj
	@echo ... src/uc/2way/node.i
	@echo ... src/uc/2way/node.s
	@echo ... src/uc/2way/print_circuit.obj
	@echo ... src/uc/2way/print_circuit.i
	@echo ... src/uc/2way/print_circuit.s
	@echo ... src/uc/2way/valiant.obj
	@echo ... src/uc/2way/valiant.i
	@echo ... src/uc/2way/valiant.s
	@echo ... src/uc/4way/Block.obj
	@echo ... src/uc/4way/Block.i
	@echo ... src/uc/4way/Block.s
	@echo ... src/uc/4way/UCNode.obj
	@echo ... src/uc/4way/UCNode.i
	@echo ... src/uc/4way/UCNode.s
	@echo ... src/uc/4way/ValiantEUG.obj
	@echo ... src/uc/4way/ValiantEUG.i
	@echo ... src/uc/4way/ValiantEUG.s
	@echo ... src/uc/4way/ValiantUC.obj
	@echo ... src/uc/4way/ValiantUC.i
	@echo ... src/uc/4way/ValiantUC.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

